typography_spectrum: 0.5442165653221309
color:
  brandColors:
    - '#040402'
    - '#302E29'
    - '#776E54'
    - '#FDF3B4'
    - '#9A9B88'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7085106
analytics:
  google: null
  facebook: null
  twitter: null
name: A Federal Source
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About Us
    id: f64afd68-28a1-4b27-a0b3-c26cd1ec695f
    type: content
favicon: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: 'A Federal Source, LLC'
description: '"One Stop Shop for Green-Building"'
purpose: []
