typography_spectrum: 0.5442165653221309
color:
  brandColors:
    - '#040402'
    - '#302E29'
    - '#776E54'
    - '#FDF3B4'
    - '#9A9B88'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7085106
analytics:
  google: null
  facebook: null
  twitter: null
name: A Federal Source
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: "A Green Alternative\_focus on reliable, high quality, high efficiency, and cost-effective products.  Our mission is to develop long lasting relationships between Government Agencies and suppliers that support the \"Green Energy\" objectives for future business development.\_ Our purchasing capability and the competitiveness of our suppliers are strategic core elements of our company making it truly simple to go with the green alternative. \_ \_ We understand\_that teaming with the right companies that share this mission is extremely important. \_We provide assistance to the government by bridging the gap between the government's purchasing agents and suppliers whose productivity & efficiency\_has been\_successful from\_their environmental performances. \_\_\_ \_ We are a source for the government agency\_that requires the supply chain of\_large manufacturers who want to save money while reducing pollution and preserving resources. \_ We Offer: \_ \_ •\tNew & Replacement LED Lighting •\tSolar PV Installations •\tConstruction & Renovation Services •\tInnovative Furniture •\tEco-friendly Office Supplies & Environmental Products •\tPersonnel Support Services"
    id: 37d1db13-b52c-497a-9cec-f0e4f694acce
    type: content
  - name: About
    id: f64afd68-28a1-4b27-a0b3-c26cd1ec695f
    type: content
favicon: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: 'A Federal Source, LLC'
description: '"One Stop Shop for Green-Building"'
purpose: []
