name: A Federal Source
favicon: null
layout_spectrum: 0.20826453831978142
typography_spectrum: 0.5442165653221309
title: '"One-Stop Shop for Green Building"'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f9f9'
    - '#7c9dd0'
    - '#365596'
    - '#5cac19'
    - '#040301'
  brandStrength: 0.3107743358705193
  lightness: 0.6783252356108278
  saturation: 0.9221927851904184
  rhythmicContrast: 0.18747694417834282
purpose: []
