name: A Federal Source
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5442165653221309
title: 'A Federal Source, LLC'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#016239'
    - '#000000'
    - '#7f8084'
    - '#dd2f23'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
